### ISSUE TITLE
Make Join us connect to the current membership system somehow

### ISSUE THREAD

**Issue by Topperfalkon** [ppuk/jekyll-site#16]
Join us currently directs to a page in the new experience, we should either modify this page to direct to the correct parts of the current membership (will make integrating new backend potentially easier down the line), or just make the links themselves direct to the current membership backend

**Comment by Topperfalkon** [comment]
Discussed this a bit with Rebecca at London meetup. The drupal membership page looks utter shite, so I might try and re-work this page to link out to the individual product pages for membership and reduced membership.

We'll also want to work out something for one-off donations, but maybe that's just a case of letting people find that through the member's portal for now or something?

**Comment by bexsentance** [comment]
Re: one-off donations, I think we should make it as easy for people as possible xD Why not just put a button on the front page labelled "Donate to the Pirate Party UK" and then underneath a link/button reading "or find out about other ways to contribute" which links to the Join Us page?

**Comment by Topperfalkon** [comment]
Closed via #25

**Comment by HeadOpener** [comment]
the about us page ( https://staging.pirateparty.org.uk/about-us/ )  link to become a pirate still directs to  https://staging.pirateparty.org.uk/pripoj-se/
