### ISSUE TITLE
"You can have it all" graphic has broken link, redirects to homepage

### ISSUE THREAD

**Issue by Topperfalkon** [ppuk/jekyll-site#18]
Find out what the thing it should have been linking to was, and either fix it, or if it shouldn't actually be a link, remove the link

**Comment by Topperfalkon** [comment]
"oh one more for now I promise under the PPUK graphic of you can have it all there is a link to https://staging.pirateparty.org.uk/snemovna which is circular or empty  by the looks of things"

**Comment by PirateLennon** [comment]
snomovna = policy effectively - which is where it was posting to on the Czech site. Given the graphic I propose that it links to /policy/

**Comment by Topperfalkon** [comment]
Fixed via #30
