### ISSUE TITLE
Czech Picture, missing quote and Czech Manifesto

### ISSUE THREAD

**Issue by HeadOpener** [ppuk/jekyll-site#23]
https://staging.pirateparty.org.uk/policy/ 
page there is a Czech PP bus picture
Also a quote from Sam which needs an actual quote.
"Some inspirational quotes about why we do really good policy and how it works
As well as something about principles etc. Sam Mills, Policy Co-Ordinator"
Also the Manifesto link further down the page links to the Czech Manifesto

**Comment by PirateLennon** [comment]
Also, the header bar picture on the right hand side of people is a group of Czech Pirates

**Comment by Topperfalkon** [comment]
fixed via #28
