### ISSUE TITLE
About Us page header has Czech folks photo on. also missing a drop down

### ISSUE THREAD

**Issue by HeadOpener** [ppuk/jekyll-site#24]
Top right has Czech PP people photo.
The drop down selector of about us has our people and local branches but not the constitution, which is also a sub header on the page though.

**Comment by Topperfalkon** [comment]
Moving this out of the live release, don't believe it's critical

**Comment by bexsentance** [comment]
> 
> 
> Moving this out of the live release, don't believe it's critical

@Topperfalkon See, we already have an issue for it, but you didn't think it was "critical" xD

**Comment by Topperfalkon** [comment]
Well, I was right, but I was assuming we'd have released already

**Comment by bexsentance** [comment]
I think it's important to remove them before we launch. They're pretty recognisable (especially if you're a Pirate)

**Comment by Topperfalkon** [comment]
Ok... I'll put it back on the list :D
