### ISSUE TITLE
Copy edits on 'What we believe' page

### ISSUE THREAD

**Issue by bexsentance** [ppuk/jekyll-site#26]
- "Human Dignity is inviolable. Each of us has a right to life and to live, to freedom of thought and self determination, and to participarte in society." - Dignity should be lower-case, and "participate" is typoed

- "The Pirate Party Develops Policy in a collaborative manner" - "Develops" and "policy" should be lower-case

- "The result is a broad range of principles, that our candidates will be proud to stand on." No comma needed

Also: are we still referring to our manifesto as "crowd-sourced"? I thought we didn't do that any more.

**Comment by Topperfalkon** [comment]
Technically the manifesto is sourced from the same suite of policies that we originally crowd-sourced, albeit heavily modified since.

**Comment by Topperfalkon** [comment]
Closed via #27
