### ISSUE TITLE
Add Volunteering tier to Join Us page

### ISSUE THREAD

**Issue by bexsentance** [ppuk/jekyll-site#38]
Join Us page https://staging.pirateparty.org.uk/join-us/ needs to have a tier for folks who want to get involved in a volunteer capacity.

- Could have a "View Open Roles" button that directs to the Vacancies page
- And/or a link to our new #volunteering channel in Discord?

**Comment by Topperfalkon** [comment]
Need to figure out how to add this to the page sensibly. Maybe a wide box underneath?
